version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on: 
      - api
    networks:
      - app-connect

  mongo:
    image: mongo
    container_name: mongodb
    # volumes:
    #   - ./data-node:/data/db
    ports: 
      - 27020:27017
    networks:
      - app-connect

  api:
    build: ../back
    networks:
      - app-connect
    ports:
      - '3001:3001'
    depends_on:
      - mongo


  


networks:
  app-connect:
      driver: bridge


